language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install mpmath"
  - "pip install nose"
before_script:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
script:
  - "make nosetest"
